apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipments-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipments-app
  template:
    metadata:
      labels:
        app: shipments-app
    spec:
      containers:
      - name: shipments-container
        image: shipments-app:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000