# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlogs.proto\x12\x07logs.v1\">\n\x10NotifyLogRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\"?\n\x11NotifyLogResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06stored\x18\x03 \x01(\x08\"(\n\x17GetNotificationsRequest\x12\r\n\x05limit\x18\x01 \x01(\r\"_\n\x0cNotification\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0e\n\x06log_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\t\x12\x13\n\x0breceived_at\x18\x05 \x01(\t\"c\n\x18GetNotificationsResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05total\x18\x02 \x01(\r\x12,\n\rnotifications\x18\x03 \x03(\x0b\x32\x15.logs.v1.Notification2\xb1\x01\n\x0bLogsService\x12I\n\x10NotifyLogCreated\x12\x19.logs.v1.NotifyLogRequest\x1a\x1a.logs.v1.NotifyLogResponse\x12W\n\x10GetNotifications\x12 .logs.v1.GetNotificationsRequest\x1a!.logs.v1.GetNotificationsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFYLOGREQUEST']._serialized_start=23
  _globals['_NOTIFYLOGREQUEST']._serialized_end=85
  _globals['_NOTIFYLOGRESPONSE']._serialized_start=87
  _globals['_NOTIFYLOGRESPONSE']._serialized_end=150
  _globals['_GETNOTIFICATIONSREQUEST']._serialized_start=152
  _globals['_GETNOTIFICATIONSREQUEST']._serialized_end=192
  _globals['_NOTIFICATION']._serialized_start=194
  _globals['_NOTIFICATION']._serialized_end=289
  _globals['_GETNOTIFICATIONSRESPONSE']._serialized_start=291
  _globals['_GETNOTIFICATIONSRESPONSE']._serialized_end=390
  _globals['_LOGSSERVICE']._serialized_start=393
  _globals['_LOGSSERVICE']._serialized_end=570
# @@protoc_insertion_point(module_scope)
