events {}

http{
    server{
        listen 8080;
        location /api/invoices/{
            proxy_pass http://invoices-svc-s05:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;}

        location /api/other/{
            proxy_pass http://other-service:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;}}}