# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x06photos\"\x1a\n\x0cPhotoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"?\n\rPhotoResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t2H\n\rPhotosService\x12\x37\n\x08GetPhoto\x12\x14.photos.PhotoRequest\x1a\x15.photos.PhotoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHOTOREQUEST']._serialized_start=25
  _globals['_PHOTOREQUEST']._serialized_end=51
  _globals['_PHOTORESPONSE']._serialized_start=53
  _globals['_PHOTORESPONSE']._serialized_end=116
  _globals['_PHOTOSSERVICE']._serialized_start=118
  _globals['_PHOTOSSERVICE']._serialized_end=190
# @@protoc_insertion_point(module_scope)
