# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import logs_pb2 as logs__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in logs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyLogCreated = channel.unary_unary(
                '/logs.v1.LogsService/NotifyLogCreated',
                request_serializer=logs__pb2.NotifyLogRequest.SerializeToString,
                response_deserializer=logs__pb2.NotifyLogResponse.FromString,
                _registered_method=True)
        self.GetNotifications = channel.unary_unary(
                '/logs.v1.LogsService/GetNotifications',
                request_serializer=logs__pb2.GetNotificationsRequest.SerializeToString,
                response_deserializer=logs__pb2.GetNotificationsResponse.FromString,
                _registered_method=True)


class LogsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NotifyLogCreated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyLogCreated': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyLogCreated,
                    request_deserializer=logs__pb2.NotifyLogRequest.FromString,
                    response_serializer=logs__pb2.NotifyLogResponse.SerializeToString,
            ),
            'GetNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotifications,
                    request_deserializer=logs__pb2.GetNotificationsRequest.FromString,
                    response_serializer=logs__pb2.GetNotificationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logs.v1.LogsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logs.v1.LogsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NotifyLogCreated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logs.v1.LogsService/NotifyLogCreated',
            logs__pb2.NotifyLogRequest.SerializeToString,
            logs__pb2.NotifyLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logs.v1.LogsService/GetNotifications',
            logs__pb2.GetNotificationsRequest.SerializeToString,
            logs__pb2.GetNotificationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
