events {}

http {
    server {
        listen 80;

        location /api/logs/ {
            proxy_pass http://logs-svc-s05:8000/logs/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location = /api/logs/summary {
            proxy_pass http://logs-svc-s05:8000/logs/summary;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }}}
